# Streamlit secrets configuration
# Create this file in .streamlit/secrets.toml in your project root

[default]
# OpenWeatherMap API Configuration
# Get your free API key from: https://openweathermap.org/api
OPENWEATHER_API_KEY = "e9c89f504c538ae2ae219b76886d0a46"

# Optional: Other API keys for enhanced features
# GOOGLE_MAPS_API_KEY = "IzaSyDE5MxNeX9YTaR0C5YUOoDesuXuH-5yjUQ"
# MAPBOX_ACCESS_TOKEN = "your_mapbox_token"

# App Configuration
APP_TITLE = "Climatrack • Real-time Weather Intelligence"
DEFAULT_UNITS = "metric"
DEFAULT_THEME = "aurora"